export const JobData = [
    {
        id: 1,
        jobTitle: "Frontend Developer",
        companyName: "XYZ Company Limited",
        jobCountry: "USA",
        jobState: "California",
        jobCity: "Silicon Valley",
        jobMode: "Remote",
        jobType: "Contract",
        jobExp: "fresher",
        companyEmpCount: 100,
        companyType: "Software Company",
        skills: ["ReactJS", "Next.js", "HTML", "CSS"],
        applyLink: "",
        jobDesc: "We are seeking a talented Frontend Developer to join our team...",
    },
    {
        id: 2,
        jobTitle: "Full Stack Developer",
        companyName: "ABC Tech Solutions",
        jobCountry: "Canada",
        jobState: "Ontario",
        jobCity: "Toronto",
        jobMode: "Onsite",
        jobType: "Permanent",
        jobExp: "fresher",
        companyEmpCount: 250,
        companyType: "Tech Startup",
        skills: ["Node.js", "React", "MongoDB", "Express"],
        applyLink: "",
        jobDesc: "ABC Tech Solutions is looking for a skilled Full Stack Developer...",
    },
    {
        id: 3,
        jobTitle: "Data Scientist",
        companyName: "Data Insight Inc.",
        jobCountry: "UK",
        jobState: "London",
        jobCity: "London",
        jobMode: "Hybrid",
        jobType: "Full-Time",
        jobExp: "frehser",
        companyEmpCount: 50,
        companyType: "Data Analytics Firm",
        skills: ["Python", "Machine Learning", "Data Analysis", "Statistics"],
        applyLink: "https://example.com/apply",
        jobDesc: "Data Insight Inc. is hiring a Data Scientist to work on cutting-edge projects...",
    },
    {
        id: 4,
        jobTitle: "UI/UX Designer",
        companyName: "Design Innovations Ltd.",
        jobCountry: "Australia",
        jobState: "New South Wales",
        jobCity: "Sydney",
        jobMode: "Onsite",
        jobType: "Contract",
        jobExp: "frehser",
        companyEmpCount: 30,
        companyType: "Design Agency",
        skills: ["Adobe XD", "Sketch", "User Research", "Prototyping"],
        applyLink: "https://example.com/apply",
        jobDesc: "Design Innovations Ltd. is seeking a talented UI/UX Designer...",
    },
    {
        id: 5,
        jobTitle: "Software Engineer",
        companyName: "Tech Solutions Ltd.",
        jobCountry: "USA",
        jobState: "New York",
        jobCity: "New York City",
        jobMode: "Remote",
        jobType: "Full-Time",
        jobExp: "frehser",
        companyEmpCount: 150,
        companyType: "IT Services",
        skills: ["Java", "Spring Boot", "Microservices", "RESTful APIs"],
        applyLink: "",
        jobDesc: "Tech Solutions Ltd. is looking for a skilled Software Engineer to join our team...",
    }
];
